### ISSUE TITLE
Possibility to get a movie logo

### ISSUE THREAD

**Issue by ORRNY66** [MoviebaseApp/tmdb-api#12]
It would be great to add the opportunity to get movie logos.
Thanks a lot.

[https://image.tmdb.org/t/p/original/5TjlgYl3DTYRIOlpjqylAgcHVBF.png](
https://image.tmdb.org/t/p/original/5TjlgYl3DTYRIOlpjqylAgcHVBF.png)

[https://api.themoviedb.org/3/movie/299534/images?api_key=84bf934f6f348e09a8de2b9b556c09ae&language=en-US&include_image_language=en](https://api.themoviedb.org/3/movie/299534/images?api_key=84bf934f6f348e09a8de2b9b556c09ae&language=en-US&include_image_language=en)

![movie_logos](https://user-images.githubusercontent.com/5471789/173344534-a9dcf5f8-86f7-4e4b-8188-82557b296bda.png)

**Comment by chrisnkrueger** [comment]
Hey, you can build the URL by the TmdbImageUrlBuilder class. For example:
`val url = TmdbImageUrlBuilder.buildPoster(item = movie, width = 200)`

The library Glide or Picasso can be used for loading the image URL.

**Comment by ORRNY66** [comment]
I'm very sorry I didn't answer before, I was busy. Thank you for your answer. Unfortunately using 
`val url = TmdbImageUrlBuilder.buildPoster (item = movie, width = 200)`
I only get movie posters. I would like to, but get the movie logo.
Thanks a lot
