### ISSUE TITLE
Crash due to missing gender

### ISSUE THREAD

**Issue by edmundjohnson** [MoviebaseApp/tmdb-api#4]
When calling:

    Tmdb3.find.find("tt10919380", "en", TmdbExternalSource.IMDB)

I get an error:

    app.moviebase.tmdb.model.TmdbGender does not contain element with name '3'

It would probably be fixed by adding the following to TmdbGender:

    @SerialName("3")
    NON_BINARY(3),

Thank you!

**Comment by chrisnkrueger** [comment]
Hi @edmundjohnson,

Thank you very much for the bug report :)! I added the gender and more tests in version 0.5.1.

**Comment by edmundjohnson** [comment]
You're welcome! And thanks for the fix, all working now.
